[global]
   workgroup = WORKGROUP
   server string = Samba Docker
   security = user
   passdb backend = tdbsam
   map to guest = Bad User
   log file = /var/log/samba/log.%m
   max log size = 50
   server role = standalone server
   dns proxy = no

   # Limita el acceso a tu LAN (192.168.100.0/24) y localhost
   hosts allow = 192.168.100. 127.

[archivos]
   path = /share/archivos
   browseable = yes
   read only = no
   writable = yes
   guest ok = no
   valid users = admin
   force user = nobody
   create mask = 0664
   directory mask = 0775
