services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    networks:
      - lab-net
    volumes:
      - ./logs:/var/log/suricata
      - ./rules:/etc/suricata/rules
      - ./etc:/etc/suricata/local
    command: ["/bin/sh","-lc","suricata-update update-sources && suricata-update && exec suricata -i eth0 -k none -l /var/log/suricata"]
    restart: unless-stopped

networks:
  lab-net:
    driver: bridge
