services:
  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    hostname: kali.assr.local
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./work:/root/work
    dns:
      - 172.30.0.10
    networks:
      assr-net:
        ipv4_address: 172.30.0.20
    command: >
      bash -lc "
      apt-get update &&
      apt-get install -y iproute2 iputils-ping curl wget netcat-traditional dnsutils &&
      bash
      "

networks:
  assr-net:
    external: true